# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Cat.create(title: 'Curious Cat', caption: 'gray cat on hind legs', image: 'https://images.pexels.com/photos/774731/pexels-photo-774731.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')
Cat.create(title: 'Sphynx Cat', caption: 'sphynx cat curled up looking at the camera', image: 'https://images.pexels.com/photos/991831/pexels-photo-991831.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'King Cat', caption: 'A cream colored cat wearing a crown and a bow', image: 'https://images.pexels.com/photos/1314550/pexels-photo-1314550.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Black and White Kitten', caption: 'A white kitten with a black spot on its ears looking right', image: 'https://images.pexels.com/photos/1120049/pexels-photo-1120049.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Perch', caption: 'A fluffy ragdoll cat sitting on the back of a computer chair in a room', image: 'https://images.pexels.com/photos/954720/pexels-photo-954720.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Comfy', caption: 'A calico cat laying on a white fluffy blanket', image: 'https://images.pexels.com/photos/266784/pexels-photo-266784.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Black Cat', caption: 'A fluffy black cat crouching and looking at the camera', image: 'https://images.pexels.com/photos/4601871/pexels-photo-4601871.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Confident', caption: 'A calico tabby mixed cat laying on a bed with its front paws crossed', image: 'https://images.pexels.com/photos/208984/pexels-photo-208984.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Peeking Out', caption: 'Fluffy orange and white kitten halfway peaking out from a curtain', image: 'https://images.pexels.com/photos/320014/pexels-photo-320014.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Sunny Kitten', caption: 'Tabby kitten sitting in a yellow sunny field', image: 'https://images.pexels.com/photos/669015/pexels-photo-669015.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'String Lights', caption: 'A tabby cat laying on a pile of string lights', image: 'https://images.pexels.com/photos/923360/pexels-photo-923360.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Stroll', caption: 'Black kitten walking along a sun dappled sidewalk', image: 'https://images.pexels.com/photos/1510543/pexels-photo-1510543.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')
Cat.create(title: 'In a Tree', caption: 'A ragdoll fluffy cat sitting in a tree', image: 'https://images.pexels.com/photos/1653357/pexels-photo-1653357.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Snowy Cat', caption: 'A black cat with orange eyes covered in snow', image: 'https://images.pexels.com/photos/302280/pexels-photo-302280.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Big Yawn', caption: 'Fluffy brown and white cat yawning', image: 'https://images.pexels.com/photos/1765832/pexels-photo-1765832.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Teef', caption: 'A tabby cat face sleeping with its fangs poking out', image: 'https://images.pexels.com/photos/271889/pexels-photo-271889.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Domino', caption: 'Black and white cat laying on a white blanket', image: 'https://images.pexels.com/photos/680994/pexels-photo-680994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Mom', caption: 'An orange tabby cat with an identical looking kitten sleeping on its back', image: 'https://images.pexels.com/photos/1096091/pexels-photo-1096091.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Big Stretch', caption: 'A ginger abyssinian cat stretching ', image: 'https://images.pexels.com/photos/3643714/pexels-photo-3643714.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Heterochromia', caption: 'A white fluffy cat with one yellow eye and one blue eye', image: 'https://images.pexels.com/photos/1981158/pexels-photo-1981158.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Fluffy Calico', caption: 'A fluffy calico cat laying down and looking up', image: 'https://images.pexels.com/photos/1359312/pexels-photo-1359312.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Siamese', caption: 'A siamese cat curled up on a well lit couch', image: 'https://images.pexels.com/photos/341522/pexels-photo-341522.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'Relaxing', caption: 'A black kitten curled up outside squinting up at the sky', image: 'https://images.pexels.com/photos/1636298/pexels-photo-1636298.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Cat.create(title: 'In the Garden', caption: 'Grey cat walking in a garden', image: 'https://images.pexels.com/photos/2261566/pexels-photo-2261566.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')


Monochrome.create(title: 'Shrine Gate', caption: 'black and white photo of a Japanese shrine gate', image: 'https://images.pexels.com/photos/301614/pexels-photo-301614.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Reaching Out', caption: 'black and white photo of a shadowy man reaching out to the camera', image: 'https://images.pexels.com/photos/167964/pexels-photo-167964.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'City Plane', caption: 'A jet flying over a city from a ground view', image: 'https://images.pexels.com/photos/2008426/pexels-photo-2008426.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Rain', caption: 'rain falling on water', image: 'https://images.pexels.com/photos/459451/pexels-photo-459451.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Abandoned School', caption: 'An abandoned school in disrepair with a chair in the hallway', image: 'https://images.pexels.com/photos/162389/lost-places-old-decay-ruin-162389.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Mountain', caption: 'A mountainside', image: 'https://images.pexels.com/photos/5641977/pexels-photo-5641977.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Typewriter Quote', caption: 'A typewriter upclose with an Oscar Wilde quote: be yourself, everyone else is taken', image: 'https://images.pexels.com/photos/698324/pexels-photo-698324.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Studying', caption: 'A desk facing a brick wall with a computer with text editor open, a keep calm carry on mug, and a journal', image: 'https://images.pexels.com/photos/169573/pexels-photo-169573.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Lantern', caption: 'An old fashioned lantern on the brick ground with a house and trees in the background', image: 'https://images.pexels.com/photos/688310/light-lantern-street-black-688310.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Snowy Treeline', caption: 'A snowy treeline', image: 'https://images.pexels.com/photos/235621/pexels-photo-235621.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Desert', caption: 'Sand dunes', image: 'https://images.pexels.com/photos/2923594/pexels-photo-2923594.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Wish', caption: 'A dandelion up close', image: 'https://images.pexels.com/photos/21323/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Record Player', caption: 'A record player', image: 'https://images.pexels.com/photos/145707/pexels-photo-145707.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Road', caption: 'A road extending to the horizon of mountains', image: 'https://images.pexels.com/photos/1038935/pexels-photo-1038935.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Kitten', caption: 'A tabby kitten laying on a cat tower looking at the camera', image: 'https://images.pexels.com/photos/2527491/pexels-photo-2527491.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Gaming', caption: 'Hands holding an xbox controller', image: 'https://images.pexels.com/photos/194511/pexels-photo-194511.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Book', caption: 'A Book flipping through the pages', image: 'https://images.pexels.com/photos/159872/book-open-pages-literature-159872.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Deer Skull', caption: 'A deer skull on the roof with a brick chiminey in the background', image: 'https://images.pexels.com/photos/992731/pexels-photo-992731.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Zebra', caption: 'Up close of a zebra eye', image: 'https://images.pexels.com/photos/39245/zebra-stripes-black-and-white-zoo-39245.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Piano Keys', caption: 'Up close of paino keys', image: 'https://images.pexels.com/photos/586415/pexels-photo-586415.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')
Monochrome.create(title: 'Faucet', caption: 'A faucet pouring out water', image: 'https://images.pexels.com/photos/615326/water-tap-black-and-white-macro-615326.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')